// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TESTESWB.Contexto;

namespace TESTESWB.Migrations
{
    [DbContext(typeof(ControleContatoContext))]
    [Migration("20181124120101_V01")]
    partial class V01
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.4-rtm-31024")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("TESTESWB.Models.AreasModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Area")
                        .IsRequired();

                    b.HasKey("Id");

                    b.ToTable("Areas");
                });

            modelBuilder.Entity("TESTESWB.Models.ContatoModel", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd();

                    b.Property<Guid>("IdArea");

                    b.Property<Guid>("IdEmpresa");

                    b.Property<string>("NomeUsuario")
                        .IsRequired();

                    b.Property<int>("Telefone");

                    b.HasKey("id");

                    b.HasIndex("IdArea");

                    b.HasIndex("IdEmpresa");

                    b.ToTable("Contato");
                });

            modelBuilder.Entity("TESTESWB.Models.EmpresaModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Nome");

                    b.HasKey("Id");

                    b.ToTable("Empresa");
                });

            modelBuilder.Entity("TESTESWB.Models.ContatoModel", b =>
                {
                    b.HasOne("TESTESWB.Models.AreasModel", "Areas")
                        .WithMany("Contato")
                        .HasForeignKey("IdArea")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("TESTESWB.Models.EmpresaModel", "Empresas")
                        .WithMany("Contato")
                        .HasForeignKey("IdEmpresa")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
